module.exports = {
  products: [
    {
      _id: '1',
      name: 'Classical Comfortable Grey Sofa',
      category: 'Sofa',
      image: 'https://github.com/yikevding/emazon/blob/main/image/sofa.jpeg?raw=true',
      price: 51299.99,
      brand: 'IKEA',
      rating: 5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Advanced Gaming Chair',
      category: 'Chair',
      image: 'https://github.com/yikevding/emazon/blob/main/image/gaming%20chair.jpeg?raw=true',
      price: 299.99,
      brand: 'MSI',
      rating: 4,
      numReviews: 51,
    },
    {
      _id: '3',
      name: 'White Marble Dinning Table',
      category: 'Table',
      image: 'https://github.com/yikevding/emazon/blob/main/image/dinning%20table.jpeg?raw=true',
      price: 399.49,
      brand: 'IKEA',
      rating: 3,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'Stylish Nike Backpack',
      category: 'Backpack',
      image: 'https://github.com/yikevding/emazon/blob/main/image/bag.jpeg?raw=true',
      price: 59.99,
      brand: 'Nike',
      rating: 5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Simple Study Desk, Home & Office Use',
      category: 'Desk',
      image: 'https://github.com/yikevding/emazon/blob/main/image/study%20desk.jpeg?raw=true',
      price: 239.99,
      brand: 'IKEA',
      rating: 4,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '6',
      name: '27 inch Advanced Monitor, 4K resolution, 144Hz',
      category: 'Monitor',
      image: 'https://github.com/yikevding/emazon/blob/main/image/monitor.jpeg?raw=true',
      price: 799.99,
      brand: 'Samsung',
      rating: 4,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};
